### ISSUE TITLE
UserClaimsFactory doesn't add role claims if supported

### ISSUE THREAD

**Issue by ajtowf** [IdentityServer/IdentityServer4.AspNetIdentity#15]
Created a pull request that fixes this https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/pull/14

**Comment by dls314** [comment]
@ajtowf  Have you found the cause of the behavior you're seeing here?

I notice that in your changes, you're directly using the "role" text as the claim type w/o looking to the IdentityOptions singleton the way that the base class does. If the base class is getting a different text in [UserClaimsPrincipalFactory.CreateAsync#L101](https://github.com/aspnet/Identity/blob/release/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs#L101) , the behavior you describe (only working after your changes) would happen.

If the IdentityOptions singleton has another value for identityOptions.ClaimsIdentity.RoleClaimType, I'd  expect the subject and name claim types would be wrong as well since they're usually set together. However, even if those subject and name claim types are incorrect in IdentityOptions, the other logic in UserClaimsFactory.CreateAsync would fix them them up as it goes along. If it does fix them up, you wouldn't see the effect anywhere but in the roles (see [UserClaimsFactory#L34](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/UserClaimsFactory.cs#L34) and [UserClaimsFactory#L39](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/UserClaimsFactory.cs#L39)).

As a blind guess of how it might all end up like that, I'd make sure that you are calling [IdentityServerBuilderExtensions.AddAspNetIdentity](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServerBuilderExtensions.cs#L21) in your Startup class's ConfigurServices method.

**Comment by ajtowf** [comment]
@dls314 interesting comment, but I'm using IdentityServerBuilderExtensions.AddAspNetIdentity, I've must've done something else wrong, because now I'm getting the roles. Although I'm not using the UserClaimsFactory from this repo, I have my own implementation. BUT, the Authorize attribute when in a RP only works if the user is in at least two roles: https://github.com/aspnet/Security/issues/1018 

Seems like the result must be in an array.

**Comment by ajtowf** [comment]
Check this out, this is what I get from my own UserClaimsFactory: 
![image](https://cloud.githubusercontent.com/assets/3427270/20122155/0590c140-a616-11e6-9bc6-cd5ef4619925.png)

And when I debug the client (an MVC app) I get the following claims:
![image](https://cloud.githubusercontent.com/assets/3427270/20122172/196319de-a616-11e6-868e-fdab123d447b.png)

For some reason I have two different roletypes for roles on the receiving end. Which is confusing and might be a part of the problem.

**Comment by ajtowf** [comment]
This is very strange, because when debugging from the "account" page within my identityserver the claims look right: Who's adding the roleclaimtype "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" that I get from the mvc client? 

![image](https://cloud.githubusercontent.com/assets/3427270/20132795/edf01ee2-a664-11e6-9a2f-2b9e71125d98.png)

Also, the AuthroizeAttribute still only seems to work if I'm in at least two roles.

**Comment by ajtowf** [comment]
Oh my god, just added the following line to the MVC app and everything looked fine and worked as expected after that.

    JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

![image](https://cloud.githubusercontent.com/assets/3427270/20133967/f0cbef56-a669-11e6-9046-81b5c30cc345.png)

Sorry for wasting your time!
